services:

  todo:
    build:
      context: ./todo
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password
    depends_on:
      - db
    networks:
      - todo-network


  stats-api:
    build:
      context: ./stats-api
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - todo-network


  db:
    image: postgres:17
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_DB: todo_db
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - todo-network


networks:
  todo-network:
    driver: bridge


volumes:

  postgres_data: