services:
  todo:
    build: 
      context: ./todo/docker
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"
    environment:
      - DB_HOST: postgres
      - DB_PORT: 5432
      - DB_NAME: todo_db
      - DB_USER: todo_user
      - DB_PASSWORD: todo_password
    depends_on:
      - db

  
  stats-api:
    build: 
      context: ./stats-api/docker
      dockerfile: Dockerfile
    
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: todo_user 
      POSTGRES_DB: todo_db
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    
  

  