name: CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: todo_user
          POSTGRES_DB: todo_db
          POSTGRES_PASSWORD: todo_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U todo_user -d todo_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Initialize database
        run: |
          PGPASSWORD=todo_password psql \
            -h localhost \
            -U todo_user \
            -d todo_db \
            -f database/init.sql

      - name: Install dependencies
        run: |
          cd todo
          npm ci

      - name: Run tests
        run: |
          cd todo
          npm test

  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: test

    if: github.ref == 'refs/heads/main'

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if image already exist
        id: check_image
        run: |
          if docker manifest inspect \
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ github.sha }} > dev/null 2>&1
          then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image if needed
        if: steps.check_image.outputs.exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: ./todo
          file: ./todo/docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ github.sha }}
        
      
  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
        - uses: actions/checkout@v4

        - name: Start SSH agent
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

        - name: Copy compose file
          run: |
                scp \
                -P ${{ secrets.DEPLOY_PORT }} \
                ./todo/compose.yml \
                ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/srv/todo/compose.yml

        - name: Deploy application
          run:
            ssh \
              -p ${{ secrets.DEPLOY_PORT }} \
              ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
              "cd /srv/todo && TAG=${{ github.sha }} docker compose up -d"

        - name: Health check
          run: |
            curl http://localhost/health

